
package net.tecgurus.cteservice._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "cteServicePortType", targetNamespace = "http://www.tecgurus.net/cteService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CteServicePortType {


    /**
     * 
     * @param cteRequest
     * @return
     *     returns net.tecgurus.cteservice._1.ClienteResponse
     */
    @WebMethod(action = "http://www.tecgurus.net/cteService/listarClientesOperation")
    @WebResult(name = "cliente_response", targetNamespace = "http://www.tecgurus.net/cteService/1.0", partName = "cte_response")
    public ClienteResponse listarClientesOperation(
        @WebParam(name = "cliente_request", targetNamespace = "http://www.tecgurus.net/cteService/1.0", partName = "cte_request")
        ClienteRequest cteRequest);

    /**
     * 
     * @param altaRequest
     * @return
     *     returns net.tecgurus.cteservice._1.ClienteAltaResponse
     */
    @WebMethod(action = "http://www.tecgurus.net/cteService/altaOperation")
    @WebResult(name = "cliente_alta_response", targetNamespace = "http://www.tecgurus.net/cteService/1.0", partName = "alta_response")
    public ClienteAltaResponse altaOperation(
        @WebParam(name = "cliente_alta_request", targetNamespace = "http://www.tecgurus.net/cteService/1.0", partName = "alta_request")
        ClienteAltaRequest altaRequest);

}
